apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-gitops-operator
  namespace: aa-patrick
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator
        spec:
          remediationAction: inform
          severity: critical
          complianceType: musthave
          subscription:
            name: devspaces
            namespace: openshift-devspaces
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions:
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: install-gitops-operator-placement
  namespace: aa-patrick
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-gitops-operator-placement
  namespace: aa-patrick
placementRef:
  name: install-gitops-operator-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: install-gitops-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
